# Use a Node.js base image
FROM node:20-alpine

# Set the working directory for the container
WORKDIR /app

# Copy and install client dependencies
COPY client/package*.json ./
RUN npm install --legacy-peer-deps

# Copy the client source code
COPY client/ .

# Run the client linter (or any other command)
CMD ["npm", "run", "lint"]
